plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.objectlife.statelayoutsample'
    compileSdk = 36

    defaultConfig {
        applicationId = 'com.objectlife.statelayoutsample'
        minSdk = 21
        targetSdk = 36
        versionCode = 1
        versionName = '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':statelayout')
}
